version: "3.8"
services:
  mysql-db:
    image: mysql:latest
    networks:
      - backend
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    ports:
      - "3306:3306"
    volumes:
      - ./database/test_schema.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql-db:/var/lib/mysql

networks:
  backend:

volumes:
  mysql-db:
